### ISSUE TITLE
Configuration with Tab Theme

### ISSUE THREAD

**Issue by mikefedak** [cmndrbensisko/LocalLayer#13]
Hello,

I have been trying to use the local layers widget with the Tab Theme but have been unsuccessful in getting the widget to be registered with this theme, are there any special instructions?

**Comment by rscheitlin** [comment]
Mike,

   The default theme in WAB is the foldable theme so adding the Local Layer widget to the Tab theme involves a few more steps.

``` Javascript
Example:
    "widgetOnScreen": {
        "widgets": [
            {
                "uri": "widgets/LocalLayer/Widget",
                "visible": false
            },
        ...
        ]
    }
```
1. open the client\stemapp\themes\TabTheme\layouts\layout1\config.json in a text editor and add the code block above. This will take care of adding the Local Layer widget to layout1
2. open the client\stemapp\themes\TabTheme\layouts\default\config.json in a text editor and add the code block above. This will take care of adding the Local Layer widget to default

**Comment by mikefedak** [comment]
Hello, 

Thanks for the help. I only needed to add the widget to the default theme. Adding it to Layout 1 broke things.
