### ISSUE TITLE
Problems embedding an iframe in an infoWindow when using attribute substitution

### ISSUE THREAD

**Issue by slead** [cmndrbensisko/LocalLayer#27]
I'm seeing a problem when trying to embed an iframe within an infoWindow, attached to a dynamic layer specified via the Local Layer Widget.

I've put this as the Custom source for the popup:

`iframe src="http://localhost/reports/pages/{GISID}"`
`a href="http://localhost/reports/pages/{GISID}"`

where {GISID} is a valid field within the dynamic layer. The attribute substitution for the anchor tag works correctly:

`a href="http://localhost/reports/pages/1090390" target="_blank">Open report in new tab

... but the substitution for the iframe src includes a `span` tag:

`iframe src="http://localhost/reports/pages/&lt;span class='esriNumericValue'&gt;1090390&lt;/span&gt;"></iframe`

Is this something you have control over in the Local Layer Widget, or is it a problem introduced by the WAB?

thanks

**Comment by cmndrbensisko** [comment]
That's interesting, Stephen.  What method are you using to dynamically stub that GISID value into your HTML?

**Comment by rscheitlin** [comment]
Closed due to no evidence that this issue is related to the LocalLayer widget
