### ISSUE TITLE
Create widget setting page error.

### ISSUE THREAD

**Issue by cpicciri** [cmndrbensisko/LocalLayer#36]
Hi, I am trying to install the Local Layer widget and can't get past the configuration. I have made all of the code changes mentioned at https://github.com/cmndrbensisko/LocalLayer and when I start up Web AppBuilder, I do see the Local Layer Widget icon. When I click the pencil icon to configure it, I get the following error: Create widget setting page error: widgets/LocalLayer/Widget.

I have tried this four times each time starting with a clean install of WAB and I always get the error. Any idea what I am doing wrong?

**Comment by rscheitlin** [comment]
cpicciri,  There as been MANY that have installed this without issue so I would say that you missed something small. Have you seen this guide: https://geonet.esri.com/servlet/JiveServlet/download/38-118684/TipsUsingLocalLayerWidget1.5.1.pdf

**Comment by cpicciri** [comment]
Robert,

Thanks for the quick reply. Yes, I’ve seen that PDF and followed it to the letter, plus, the additional changes from the readme for WAB 1.1 version.

I even validated the code after each change to make sure I didn’t have any typos using this site:

http://jsonformatter.curiousconcept.com/

Unfortunately, I am still getting the same error.

Carlos

**Comment by rscheitlin** [comment]
Carlos,  It would be best if you start a discussion in GeoNet  https://geonet.esri.com/discussion/create.jspa?containerType=700&containerID=1294

**Comment by cpicciri** [comment]
Okay, thanks.

**Comment by rscheitlin** [comment]
Unable to duplicate issue.
