### ISSUE TITLE
how to use local arcgis server's map service

### ISSUE THREAD

**Issue by wentmelo** [cmndrbensisko/LocalLayer#40]
As the title, may I ask some skills about how to add my local arcgis server's services into my application. Cause I found that the local Layer widget in my web appbuilder could only help me add some layer published on the arcgisonline and portal.

**Comment by rscheitlin** [comment]
Your question is clear the only confusion is how you came to this comment "local Layer widget in my web appbuilder could only help me add some layer published on the arcgisonline and portal". If read the readme.md the whole purpose of this widget is to allow you to add layer from your own ArcGIS Server instance. I am not sure how much clearer the documentation can be on this subject.

**Comment by wentmelo** [comment]
Thank you for you quick reply so much. However, when I add my local server service url (http://went.arcgiscloud.com:6080/arcgis/rest/services/Hosted/wuhu1/MapServer/21) into the widget setting window, there is a red interrogation mark showing that something wrong which I am not able to fix out. So could you help me find what's wrong with that condition? Thank you very much.
