### ISSUE TITLE
Map reloading when clicking on Widget

### ISSUE THREAD

**Issue by sahilyousif** [cmndrbensisko/LocalLayer#43]
Hi, 

I just downloaded the LocalLayer widget and followed all the instructions in the readme to install it. I am able to add the widget on the screen, but when I click on the widget the map reloads. I have not configured anything on the widget yet, the sample layers are still there, I was expecting them to appear when I click on the widget. The widget would just reload the map when i click. Any idea what I should do?

**Comment by rscheitlin** [comment]
If you followed the instructions in the read me you would have added it to the "widgetOnScreen" section. The widget is not seen anywhere in the app itself it would only appear in the widgets tab in the builder. It sounds like you did not add it to the "widgetOnScreen" section and have an actual button in your map.
![example](https://cloud.githubusercontent.com/assets/1216460/10532259/cfa4398a-7381-11e5-9c3b-69ef366e2132.jpg)

**Comment by sahilyousif** [comment]
Thanks rscheitlin. I have the widget appearing in the widget tab in the builder, just like in the image you posted. So do you mean to say that the LocalLayer widget is "not meant" to be added onto the map?

**Comment by rscheitlin** [comment]
Correct when you configure the widget using the pencil in the image above then it automatically adds the configured layers to the map and there is no button in the map itself that you would see or be able to push,

**Comment by sahilyousif** [comment]
Got it..thanks! I was actually looking for a widget that would display only selected layers from the map in panel. I wanted to add multiple such widgets in my application so that I can have layers grouped under appropriate categories. Do you know if this is possible?

**Comment by rscheitlin** [comment]
Sure it would be possible. It just currently is not developed to my knowledge.
