### ISSUE TITLE
Is it possible to add layers at run-time?

### ISSUE THREAD

**Issue by slead** [cmndrbensisko/LocalLayer#51]
The local layer widget is awesome at allowing an administrator to configure a web app, before it is published.

Is there any support for allowing end-users to add a layer to the map dynamically? Eg, when using a Web App, I want to add a new feature layer based on its REST endpoint.

**Comment by cmndrbensisko** [comment]
Possible, absolutely!  But I'm not sure if it's really in the 'scope' of the LLW. I enjoy how this widget doesn't have any UI components beyond configuration; it 'just works' in the background of the WAB.

I remember seeing another Widget in the geonet forums that had a nice UI and the functionality you're describing; Maybe using that widget in addition to LocalLayer would be another option?

**Comment by slead** [comment]
Cool, thanks for the pointers - it appears that the [Add Service Widget](https://geonet.esri.com/docs/DOC-6263) will do what I need.

Thanks again for writing such an excellent widget (which Esri really should have done in the first place!)
