### ISSUE TITLE
Local Layer Widget and WAB 2.0

### ISSUE THREAD

**Issue by slead** [cmndrbensisko/LocalLayer#53]
I tried to install the LL widget with WAB 2.0, using the instructions for WAB 1.3 and it's not working correctly.

LL Widget is now appearing as an in-panel widget - I can only add it to the Header Controller or one of the placeholder on-map widgets. But the main problem is that it doesn't actually add the layers to the map - the Legend and Layer List are both empty.

Any ideas? I hope Esri haven't deliberately tried to break this widget because it doesn't fit with their model ;)

**Comment by rscheitlin** [comment]
Stephen,

   Adam, I, Barnaby and many others have the 1.3.1. version working just fine in WAB 2.0. When you say you can only add it as to the header controller, etc leads me to believe that you are trying to add it inside the WAB UI. The readme.md instructs you to manually add it to the predefined apps config.json. Can you try that again. You will see the LL widget in the main widget choice panel without having to click on a placeholder numbered icon or add it to a widget controller.

**Comment by slead** [comment]
@rscheitlin sorry, my mistake. I've installed this widget many times on many different PCs and I guess I got careless and made a mistake on this one. I can confirm that LL widget 1.3.1 seems to work correctly on WAB 2.0. Sorry for the mixup - and keep up the great work on the most useful WAB widget ;)
