### ISSUE TITLE
Attribute Table and Secure Services

### ISSUE THREAD

**Issue by wspiking** [cmndrbensisko/LocalLayer#9]
I haven't had any luck w/ the Attribute Table working with secure services.  Does this functionality exist?

**Comment by rscheitlin** [comment]
Bill,

   I am currently leaning towards this being a WAB issue and not something limited to this widget. Can you get your data to work with the attribute table widget without using the Local Layer widget?

**Comment by wspiking** [comment]
I think it worked in the past, but I'll test to verify.  Thank you Robert.

**Comment by wspiking** [comment]
The Attribute Table is working with secure services from AGS 10.0 using the LocalLayer widget.  The issue seems to be with AGS 10.1.  I don't have access to 10.2 or 10.3 to test.  I'll continue to troubleshoot.....

**Comment by rscheitlin** [comment]
This issue is now resolved by following the instructions in the readme.
